# Generated by Django 2.2.6 on 2019-11-18 17:48

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20191118_1748'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='01359add9d184cf1bcf0738932039276f5c4673ba3784178ba7918704e4501e3', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='19b56f4941ab4e0d9acc3b104d91908ef77321f2cf4c42a2be35b2c10ca5778c', max_length=300, null=True),
        ),
    ]
