# Generated by Django 2.2.6 on 2019-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0004_auto_20191118_1749'),
    ]

    operations = [
        migrations.AlterField(
            model_name='resetpassworddata',
            name='token',
            field=models.CharField(blank=True, default='62dc7ae93d3e4447aefdea2454ea7c24ee35ebb045984a47b34d11c975b8a223', max_length=300, null=True),
        ),
        migrations.AlterField(
            model_name='user',
            name='token',
            field=models.CharField(blank=True, default='e3564932265f40bdb65cb271dd4153df01e03651fbf24f52b89f274b66021919', max_length=300, null=True),
        ),
    ]
