# Generated by Django 2.2.6 on 2019-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0002_auto_20191118_1748'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupermodel',
            name='name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
