# Generated by Django 2.2.6 on 2019-11-18 17:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0003_mysupermodel_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='mysupermodel',
            name='changed',
            field=models.BooleanField(default=False),
        ),
    ]
