# Generated by Django 2.2.6 on 2019-11-18 18:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myAPP', '0005_mysupermodel_title'),
    ]

    operations = [
        migrations.AddField(
            model_name='mysupermodel',
            name='first_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
        migrations.AddField(
            model_name='mysupermodel',
            name='last_name',
            field=models.CharField(blank=True, max_length=300, null=True),
        ),
    ]
